import type { TutorialCollection, TutorialManifest } from '../../engine/types';
import { CHEAT_COMMANDS } from '../../engine/systems/CheatSystem';
import { BETRAYAL_COMMANDS } from './game';
import {
    createExchangeReadyTutorialCore,
    createHeroAttackTraitorReadyTutorialCore,
    createJackSpiritPostReviveAttackReadyTutorialCore,
    createMummyMonsterAttackRewardReadyTutorialCore,
    createMummyMonsterMoveReadyTutorialCore,
    createMummyReadyToBanishTutorialCore,
    createMummyTraitorVictoryReadyTutorialCore,
    createSafeOmenPendingResolutionTutorialCore,
    createStartedFirstScenarioTutorialCore,
} from './testing/firstScenarioTestUtils';

const BETRAYAL_BASIC_SETUP_AND_TURN: TutorialManifest = {
    id: 'basic-setup-and-turn',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-runtime',
            content: 'game-betrayal:tutorial.basicSetup.steps.setupRuntime',
            position: 'center',
            showMask: true,
            viewAs: '0',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createStartedFirstScenarioTutorialCore().core ?? createStartedFirstScenarioTutorialCore(),
                    },
                },
            ],
        },
        {
            id: 'objective-and-turn',
            content: 'game-betrayal:tutorial.basicSetup.steps.objectiveAndTurn',
            highlightTarget: 'betrayal-action-move',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'traits-and-speed',
            content: 'game-betrayal:tutorial.basicSetup.steps.traitsAndSpeed',
            highlightTarget: 'betrayal-current-traits',
            position: 'right',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'trait-track-reading',
            content: 'game-betrayal:tutorial.basicSetup.steps.traitTrackReading',
            highlightTarget: 'betrayal-current-traits',
            position: 'right',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'moves-remaining',
            content: 'game-betrayal:tutorial.basicSetup.steps.movesRemaining',
            highlightTarget: 'betrayal-moves-remaining',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'room-board',
            content: 'game-betrayal:tutorial.basicSetup.steps.roomBoard',
            highlightTarget: 'betrayal-room-board',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'observe-teammate',
            content: 'game-betrayal:tutorial.basicSetup.steps.observeTeammate',
            highlightTarget: 'betrayal-bottom-teammate-1',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'focus-self-room',
            content: 'game-betrayal:tutorial.basicSetup.steps.focusSelfRoom',
            highlightTarget: 'betrayal-focus-self-room',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'haunt-risk-track',
            content: 'game-betrayal:tutorial.basicSetup.steps.hauntRiskTrack',
            highlightTarget: 'betrayal-haunt-risk-status',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'inventory-and-help',
            content: 'game-betrayal:tutorial.basicSetup.steps.inventoryAndHelp',
            highlightTarget: 'betrayal-inventory-zone',
            position: 'right',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'use-book',
            content: 'game-betrayal:tutorial.basicSetup.steps.useBook',
            highlightTarget: 'betrayal-inventory-omen-book',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.USE_POSSESSION],
            allowedTargets: ['omen-book'],
            advanceOnEvents: [{ type: 'POSSESSION_USED', match: { playerId: '0', cardId: 'omen-book' } }],
            viewAs: '0',
        },
        {
            id: 'open-move-targets',
            content: 'game-betrayal:tutorial.basicSetup.steps.openMoveTargets',
            highlightTarget: 'betrayal-action-move',
            position: 'top',
            viewAs: '0',
        },
        {
            id: 'move-to-hallway',
            content: 'game-betrayal:tutorial.basicSetup.steps.moveToHallway',
            highlightTarget: 'betrayal-room-hallway',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.MOVE_TO_ROOM],
            allowedTargets: ['hallway'],
            advanceOnEvents: [{ type: 'EXPLORER_MOVED', match: { playerId: '0', roomId: 'hallway' } }],
            viewAs: '0',
        },
        {
            id: 'explore-upper',
            content: 'game-betrayal:tutorial.basicSetup.steps.exploreUpper',
            highlightTarget: 'betrayal-action-explore',
            position: 'top',
            requireAction: true,
            allowedCommands: [],
            viewAs: '0',
        },
        {
            id: 'confirm-room-placement',
            content: 'game-betrayal:tutorial.basicSetup.steps.confirmRoomPlacement',
            highlightTarget: 'betrayal-room-placement-confirm',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.EXPLORE_ROOM],
            advanceOnEvents: [{ type: 'ROOM_EXPLORED', match: { playerId: '0' } }],
            viewAs: '0',
        },
        {
            id: 'finish',
            content: 'game-betrayal:tutorial.basicSetup.steps.finish',
            highlightTarget: 'betrayal-latest-discovery',
            position: 'center',
            infoStep: true,
            allowedCommands: [BETRAYAL_COMMANDS.USE_RABBIT_FOOT],
            viewAs: '0',
        },
    ],
};

const BETRAYAL_OMEN_CONFIRMATION_AND_HAUNT_RISK: TutorialManifest = {
    id: 'omen-confirmation-and-haunt-risk',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-omen-confirmation',
            content: 'game-betrayal:tutorial.omenConfirmation.steps.setupOmenConfirmation',
            position: 'center',
            showMask: true,
            viewAs: '0',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createSafeOmenPendingResolutionTutorialCore(),
                    },
                },
            ],
        },
        {
            id: 'confirm-omen-card',
            content: 'game-betrayal:tutorial.omenConfirmation.steps.confirmOmenCard',
            highlightTarget: 'betrayal-latest-discovery',
            position: 'right',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.ACKNOWLEDGE_CARD_RESOLUTION],
            aiActions: [
                {
                    commandType: BETRAYAL_COMMANDS.ACKNOWLEDGE_CARD_RESOLUTION,
                    playerId: '1',
                },
                {
                    commandType: BETRAYAL_COMMANDS.ACKNOWLEDGE_CARD_RESOLUTION,
                    playerId: '2',
                },
            ],
            autoAdvanceAfterAi: false,
            advanceOnEvents: [{ type: 'CARD_RESOLUTION_ACKNOWLEDGED', match: { playerId: '0', remainingCount: 0 } }],
            viewAs: '0',
        },
        {
            id: 'omen-confirmation-review',
            content: 'game-betrayal:tutorial.omenConfirmation.steps.review',
            highlightTarget: 'betrayal-inventory-zone',
            position: 'right',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'haunt-risk-track',
            content: 'game-betrayal:tutorial.omenConfirmation.steps.hauntRiskTrack',
            highlightTarget: 'betrayal-haunt-risk-status',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
    ],
};

const BETRAYAL_TRADE_AND_AGREEMENT: TutorialManifest = {
    id: 'trade-and-agreement',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-trade',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.setupTrade',
            position: 'center',
            showMask: true,
            viewAs: '0',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createExchangeReadyTutorialCore().core ?? createExchangeReadyTutorialCore(),
                    },
                },
            ],
            autoAdvanceAfterAi: false,
        },
        {
            id: 'choose-trade-item',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.chooseTradeItem',
            highlightTarget: 'betrayal-inventory-rope',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'choose-trade-target',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.chooseTradeTarget',
            highlightTarget: 'betrayal-room-occupant-hallway-1',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'choose-trade-return',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.chooseTradeReturn',
            highlightTarget: 'betrayal-trade-return-selector',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'send-trade-request',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.sendTradeRequest',
            highlightTarget: 'betrayal-action-trade',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.TRADE_POSSESSION],
            advanceOnEvents: [{ type: 'POSSESSION_TRADE_REQUESTED', match: { playerId: '0', targetPlayerId: '1' } }],
            viewAs: '0',
        },
        {
            id: 'request-waiting',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.requestWaiting',
            highlightTarget: 'betrayal-trade-flow-banner',
            position: 'top',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'accept-trade-request',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.acceptTradeRequest',
            highlightTarget: 'betrayal-trade-agreement-panel',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.RESOLVE_TRADE_AGREEMENT],
            advanceOnEvents: [{ type: 'POSSESSION_TRADED', match: { playerId: '0', targetPlayerId: '1' } }],
            viewAs: '1',
        },
        {
            id: 'trade-review',
            content: 'game-betrayal:tutorial.tradeAndAgreement.steps.tradeReview',
            highlightTarget: 'betrayal-room-latest-feedback',
            position: 'center',
            infoStep: true,
            viewAs: '0',
        },
    ],
};

const BETRAYAL_HAUNT_ACTIONS_AND_FINISH: TutorialManifest = {
    id: 'haunt-actions-and-finish',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-ready-to-banish',
            content: 'game-betrayal:tutorial.hauntActions.steps.setupReadyToExorcise',
            position: 'center',
            showMask: true,
            viewAs: '0',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createMummyReadyToBanishTutorialCore().core ?? createMummyReadyToBanishTutorialCore(),
                    },
                },
            ],
        },
        {
            id: 'help-entry',
            content: 'game-betrayal:tutorial.hauntActions.steps.helpEntry',
            highlightTarget: 'betrayal-open-scenario',
            position: 'center',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'haunt-actions',
            content: 'game-betrayal:tutorial.hauntActions.steps.hauntActions',
            highlightTarget: 'betrayal-action-use',
            position: 'right',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'banish-mummy',
            content: 'game-betrayal:tutorial.hauntActions.steps.banishMummy',
            highlightTarget: 'betrayal-action-use',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.BANISH_MUMMY],
            randomPolicy: { mode: 'sequence', values: [3, 3, 3, 3, 3, 1, 1, 1, 1, 1], cursor: 0 },
            advanceOnEvents: [{ type: 'MUMMY_BANISHED', match: { playerId: '0', success: true } }],
            viewAs: '0',
        },
        {
            id: 'endgame-review',
            content: 'game-betrayal:tutorial.hauntActions.steps.endgameReview',
            highlightTarget: 'betrayal-endgame-screen',
            position: 'center',
            infoStep: true,
            viewAs: '0',
        },
    ],
};

const BETRAYAL_HERO_ATTACK_PATH: TutorialManifest = {
    id: 'hero-attack-path',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-hero-attack',
            content: 'game-betrayal:tutorial.heroAttackPath.steps.setupHeroAttack',
            position: 'center',
            showMask: true,
            viewAs: '0',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createHeroAttackTraitorReadyTutorialCore().core ?? createHeroAttackTraitorReadyTutorialCore(),
                    },
                },
            ],
        },
        {
            id: 'hero-attack-objective',
            content: 'game-betrayal:tutorial.heroAttackPath.steps.heroAttackObjective',
            highlightTarget: 'betrayal-open-scenario',
            position: 'left',
            requireAction: true,
            allowedCommands: [],
            viewAs: '0',
        },
        {
            id: 'attack-traitor',
            content: 'game-betrayal:tutorial.heroAttackPath.steps.attackTraitor',
            highlightTarget: 'betrayal-room-board',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.HAUNT_ATTACK],
            randomPolicy: { mode: 'fixed', values: [3, 3, 1, 1, 1, 1, 1, 1] },
            advanceOnEvents: [{ type: 'HAUNT_ATTACK_RESOLVED', match: { attackerPlayerId: '0', target: 'traitor' } }],
            viewAs: '0',
        },
        {
            id: 'hero-attack-review',
            content: 'game-betrayal:tutorial.heroAttackPath.steps.heroAttackReview',
            highlightTarget: 'betrayal-attack-roll-review',
            position: 'center',
            infoStep: true,
            viewAs: '0',
        },
    ],
};

const BETRAYAL_JACK_SPIRIT_PATH: TutorialManifest = {
    id: 'jack-spirit-path',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-jack-spirit',
            content: 'game-betrayal:tutorial.jackSpiritPath.steps.setupJackSpirit',
            position: 'center',
            showMask: true,
            viewAs: '2',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createJackSpiritPostReviveAttackReadyTutorialCore().core ?? createJackSpiritPostReviveAttackReadyTutorialCore(),
                    },
                },
            ],
        },
        {
            id: 'jack-spirit-objective',
            content: 'game-betrayal:tutorial.jackSpiritPath.steps.jackSpiritObjective',
            highlightTarget: 'betrayal-open-scenario',
            position: 'left',
            requireAction: true,
            allowedCommands: [],
            viewAs: '2',
        },
        {
            id: 'jack-spirit-attack',
            content: 'game-betrayal:tutorial.jackSpiritPath.steps.jackSpiritAttack',
            highlightTarget: 'betrayal-room-board',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.HAUNT_ATTACK],
            randomPolicy: { mode: 'sequence', values: [3, 3, 1, 3, 2, 1, 1] },
            advanceOnEvents: [{ type: 'HAUNT_ATTACK_RESOLVED', match: { attackerPlayerId: '2', target: 'hero' } }],
            viewAs: '2',
        },
        {
            id: 'jack-spirit-review',
            content: 'game-betrayal:tutorial.jackSpiritPath.steps.jackSpiritReview',
            highlightTarget: 'betrayal-attack-roll-review',
            position: 'center',
            infoStep: true,
            viewAs: '2',
        },
    ],
};

const BETRAYAL_TRAITOR_PATH: TutorialManifest = {
    id: 'traitor-path',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-traitor-turn',
            content: 'game-betrayal:tutorial.traitorPath.steps.setupTraitorTurn',
            position: 'center',
            showMask: true,
            viewAs: '2',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createMummyTraitorVictoryReadyTutorialCore().core ?? createMummyTraitorVictoryReadyTutorialCore(),
                    },
                },
            ],
        },
        {
            id: 'traitor-objective',
            content: 'game-betrayal:tutorial.traitorPath.steps.traitorObjective',
            highlightTarget: 'betrayal-open-scenario',
            position: 'left',
            requireAction: true,
            allowedCommands: [],
            viewAs: '2',
        },
        {
            id: 'pick-up-girl',
            content: 'game-betrayal:tutorial.traitorPath.steps.pickUpGirl',
            highlightTarget: 'betrayal-action-use',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.PICK_UP_MUMMY_GIRL],
            advanceOnEvents: [{ type: 'MUMMY_GIRL_PICKED_UP', match: { playerId: '2' } }],
            viewAs: '2',
        },
        {
            id: 'give-girl-to-mummy',
            content: 'game-betrayal:tutorial.traitorPath.steps.giveGirlToMummy',
            highlightTarget: 'betrayal-action-use',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.GIVE_GIRL_TO_MUMMY],
            advanceOnEvents: [{ type: 'MUMMY_GIRL_GIVEN', match: { playerId: '2' } }],
            viewAs: '2',
        },
        {
            id: 'give-omen-to-mummy',
            content: 'game-betrayal:tutorial.traitorPath.steps.giveOmenToMummy',
            highlightTarget: 'betrayal-action-use',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.GIVE_OMEN_TO_MUMMY],
            advanceOnEvents: [{ type: 'MUMMY_OMEN_GIVEN', match: { playerId: '2', cardId: 'holy-symbol' } }],
            viewAs: '2',
        },
        {
            id: 'traitor-finish',
            content: 'game-betrayal:tutorial.traitorPath.steps.traitorFinish',
            highlightTarget: 'betrayal-endgame-screen',
            position: 'center',
            infoStep: true,
            viewAs: '2',
        },
    ],
};

const BETRAYAL_MUMMY_MONSTER_ACTIONS: TutorialManifest = {
    id: 'mummy-monster-actions',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'setup-mummy-monster-move',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.setupMonsterMove',
            position: 'center',
            showMask: true,
            viewAs: '2',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createMummyMonsterMoveReadyTutorialCore().core ?? createMummyMonsterMoveReadyTutorialCore(),
                    },
                },
            ],
            autoAdvanceAfterAi: false,
        },
        {
            id: 'mummy-monster-turn-start',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.monsterTurnStart',
            highlightTarget: 'betrayal-action-monsterTurnStart',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.RESOLVE_MONSTER_TURN_START],
            advanceOnEvents: [{ type: 'MONSTER_TURN_START_RESOLVED', match: { monsterId: 'mummy' } }],
            viewAs: '2',
        },
        {
            id: 'mummy-monster-roll',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.monsterRoll',
            highlightTarget: 'betrayal-action-monsterMovementRoll',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.ROLL_MONSTER_MOVEMENT_GROUP],
            randomPolicy: { mode: 'sequence', values: [1, 1, 1], cursor: 0 },
            advanceOnEvents: [{ type: 'MONSTER_MOVEMENT_GROUP_ROLLED' }],
            viewAs: '2',
        },
        {
            id: 'mummy-monster-roll-review',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.monsterRollReview',
            highlightTarget: 'betrayal-recent-roll-panel',
            highlightFrame: 'none',
            position: 'center',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.ACKNOWLEDGE_RECENT_ROLL],
            advanceOnEvents: [{ type: 'RECENT_ROLL_ACKNOWLEDGED' }],
            viewAs: '2',
        },
        {
            id: 'mummy-monster-move-target',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.monsterMoveTarget',
            highlightTarget: 'betrayal-room-board',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.MOVE_MONSTER_TO_ROOM],
            advanceOnEvents: [{ type: 'MONSTER_MOVED', match: { monsterId: 'mummy' } }],
            viewAs: '2',
        },
        {
            id: 'mummy-monster-move-result',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.monsterMoveResult',
            highlightTarget: 'betrayal-room-latest-feedback',
            position: 'top',
            infoStep: true,
            viewAs: '2',
        },
        {
            id: 'setup-mummy-attack',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.setupAttack',
            position: 'center',
            showMask: true,
            viewAs: '2',
            aiActions: [
                {
                    commandType: CHEAT_COMMANDS.MERGE_STATE,
                    payload: {
                        fields: createMummyMonsterAttackRewardReadyTutorialCore().core ?? createMummyMonsterAttackRewardReadyTutorialCore(),
                    },
                },
            ],
            autoAdvanceAfterAi: false,
        },
        {
            id: 'mummy-attack-forced',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.attackForced',
            highlightTarget: 'betrayal-action-monsterAttack',
            position: 'top',
            infoStep: true,
            viewAs: '2',
        },
        {
            id: 'mummy-attack-target',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.attackTarget',
            highlightTarget: 'betrayal-room-board',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.MONSTER_ATTACK_HERO],
            randomPolicy: { mode: 'sequence', values: [3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1], cursor: 0 },
            advanceOnEvents: [{ type: 'MONSTER_ATTACK_HERO_RESOLVED', match: { monsterId: 'mummy' } }],
            viewAs: '2',
        },
        {
            id: 'mummy-attack-roll-review',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.attackRollReview',
            highlightTarget: 'betrayal-recent-roll-panel',
            highlightFrame: 'none',
            position: 'center',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.ACKNOWLEDGE_RECENT_ROLL],
            advanceOnEvents: [{ type: 'RECENT_ROLL_ACKNOWLEDGED' }],
            viewAs: '2',
        },
        {
            id: 'mummy-attack-reward',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.attackReward',
            highlightTarget: 'betrayal-mummy-reward-banner',
            position: 'top',
            requireAction: true,
            allowedCommands: [BETRAYAL_COMMANDS.RESOLVE_MUMMY_ATTACK_REWARD],
            advanceOnEvents: [{
                type: 'MUMMY_ATTACK_REWARD_RESOLVED',
                match: { monsterId: 'mummy', choice: 'steal', stolenCardId: 'map' },
            }],
            viewAs: '2',
        },
        {
            id: 'mummy-steal-result',
            content: 'game-betrayal:tutorial.mummyMonsterActions.steps.stealResult',
            highlightTarget: 'betrayal-room-latest-feedback',
            position: 'top',
            infoStep: true,
            viewAs: '2',
        },
    ],
};

const BETRAYAL_TUTORIAL_CATALOG: TutorialCollection = {
    defaultTutorialId: 'basic-setup-and-turn',
    tutorials: {
        'basic-setup-and-turn': {
            titleKey: 'tutorial.basicSetup.title',
            descriptionKey: 'tutorial.basicSetup.description',
            manifest: BETRAYAL_BASIC_SETUP_AND_TURN,
        },
        'omen-confirmation-and-haunt-risk': {
            titleKey: 'tutorial.omenConfirmation.title',
            descriptionKey: 'tutorial.omenConfirmation.description',
            manifest: BETRAYAL_OMEN_CONFIRMATION_AND_HAUNT_RISK,
        },
        'trade-and-agreement': {
            titleKey: 'tutorial.tradeAndAgreement.title',
            descriptionKey: 'tutorial.tradeAndAgreement.description',
            manifest: BETRAYAL_TRADE_AND_AGREEMENT,
        },
        'move-explore-use': {
            titleKey: 'tutorial.basicSetup.title',
            descriptionKey: 'tutorial.basicSetup.description',
            manifest: BETRAYAL_BASIC_SETUP_AND_TURN,
            hiddenFromCatalog: true,
        },
        'crimson-jack-objective': {
            titleKey: 'tutorial.hauntActions.title',
            descriptionKey: 'tutorial.hauntActions.description',
            manifest: BETRAYAL_HAUNT_ACTIONS_AND_FINISH,
            hiddenFromCatalog: true,
        },
        'haunt-actions-and-finish': {
            titleKey: 'tutorial.hauntActions.title',
            descriptionKey: 'tutorial.hauntActions.description',
            manifest: BETRAYAL_HAUNT_ACTIONS_AND_FINISH,
        },
        'hero-attack-path': {
            titleKey: 'tutorial.heroAttackPath.title',
            descriptionKey: 'tutorial.heroAttackPath.description',
            manifest: BETRAYAL_HERO_ATTACK_PATH,
            hiddenFromCatalog: true,
        },
        'jack-spirit-path': {
            titleKey: 'tutorial.jackSpiritPath.title',
            descriptionKey: 'tutorial.jackSpiritPath.description',
            manifest: BETRAYAL_JACK_SPIRIT_PATH,
            hiddenFromCatalog: true,
        },
        'traitor-path': {
            titleKey: 'tutorial.traitorPath.title',
            descriptionKey: 'tutorial.traitorPath.description',
            manifest: BETRAYAL_TRAITOR_PATH,
        },
        'mummy-monster-actions': {
            titleKey: 'tutorial.mummyMonsterActions.title',
            descriptionKey: 'tutorial.mummyMonsterActions.description',
            manifest: BETRAYAL_MUMMY_MONSTER_ACTIONS,
        },
    },
};

export default BETRAYAL_TUTORIAL_CATALOG;
