export const SUMMONER_WARS_DESKTOP_HUD_REFERENCE_WIDTH_PX = 1280;
export const SUMMONER_WARS_BOARD_REFERENCE_WIDTH_PX = 1920;
export const SUMMONER_WARS_MOBILE_BOARD_REFERENCE_WIDTH_PX = 900;
export const SUMMONER_WARS_MOBILE_HAND_REFERENCE_WIDTH_PX = SUMMONER_WARS_MOBILE_BOARD_REFERENCE_WIDTH_PX;

export const BOARD_SHELL_REFERENCE_WIDTH = `var(--sw-board-reference-width, ${SUMMONER_WARS_BOARD_REFERENCE_WIDTH_PX}px)`;
