import type { CriticalImageResolver } from '../../core/types';

export const qidahenCriticalImageResolver: CriticalImageResolver = () => ({
    critical: [
        'qidahen/board/qidahen-main-map',
        'qidahen/cards/backs/ming-deck-back',
        'qidahen/cards/backs/korea-deck-back',
        'qidahen/cards/backs/qidahen-common-card-back',
        'qidahen/cards/atlases/ming-faction-deck-atlas',
        'qidahen/cards/atlases/mongol-faction-deck-atlas',
        'qidahen/cards/atlases/korea-special-deck-atlas',
        'qidahen/cards/atlases/ordinary-hand-atlas05',
        'qidahen/markers/ming-control-diplomacy-marker-a',
        'qidahen/markers/jin-control-diplomacy-marker-a',
        'qidahen/markers/chronology-year-marker',
        'qidahen/units/ming-regular-infantry-unit',
        'qidahen/units/ming-regular-cavalry-unit',
    ],
    warm: [
        'qidahen/cards/backs/mongol-deck-back',
        'qidahen/cards/backs/jin-deck-back',
        'qidahen/cards/atlases/jin-faction-deck-atlas',
        'qidahen/markers/mongol-control-diplomacy-marker-a',
        'qidahen/markers/ming-control-diplomacy-marker-b',
        'qidahen/markers/mongol-control-diplomacy-marker-b',
        'qidahen/markers/jin-control-diplomacy-marker-b',
        'qidahen/markers/drought-marker',
        'qidahen/markers/battle-defeat-marker',
        'qidahen/markers/ruin-marker',
        'qidahen/markers/hanseong-victory-point-marker',
        'qidahen/markers/imperial-seal-victory-point-marker',
        'qidahen/markers/ming-score-marker',
        'qidahen/markers/mongol-score-marker',
        'qidahen/markers/jin-score-marker',
        'qidahen/markers/jin-homeland-marker',
        'qidahen/markers/mongol-homeland-marker',
        'qidahen/units/ming-regular-artillery-unit',
        'qidahen/units/ming-mercenary-infantry-unit',
        'qidahen/units/ming-mercenary-cavalry-unit',
        'qidahen/units/ming-mercenary-artillery-unit',
        'qidahen/units/ming-chuanbing-unit',
        'qidahen/units/mongol-regular-infantry-unit',
        'qidahen/units/mongol-regular-cavalry-unit',
        'qidahen/units/mongol-regular-artillery-unit',
        'qidahen/units/mongol-mercenary-infantry-unit',
        'qidahen/units/mongol-mercenary-cavalry-unit',
        'qidahen/units/jin-regular-infantry-unit',
        'qidahen/units/jin-regular-cavalry-unit',
        'qidahen/units/jin-regular-artillery-unit',
        'qidahen/units/jin-mercenary-infantry-unit',
        'qidahen/units/jin-mercenary-cavalry-unit',
        'qidahen/units/neutral-infantry-unit',
        'qidahen/units/neutral-cavalry-unit',
    ],
});

export default qidahenCriticalImageResolver;
