import type { GameManifestEntry } from '../manifest.types';
import {
    QIDAHEN_IN_MATCH_SCENARIO_VOTE_FIELD,
    QIDAHEN_PLAYER_OPTIONS,
    QIDAHEN_PREGAME_CHOICE_FIELDS,
    QIDAHEN_SCENARIO_SETUP_OPTIONS,
    QIDAHEN_SCENARIO_SETUP_FIELD,
} from './roomSetup';

const entry: GameManifestEntry = {
    id: 'qidahen',
    type: 'game',
    enabled: true,
    statusTag: 'under_construction',
    titleKey: 'games.qidahen.title',
    descriptionKey: 'games.qidahen.description',
    category: 'wargame',
    playersKey: 'games.qidahen.players',
    icon: '恨',
    thumbnailPath: 'qidahen/thumbnails/cover',
    cursorTheme: 'qidahen-tactical',
    allowLocalMode: false,
    playerOptions: [...QIDAHEN_PLAYER_OPTIONS],
    createRoomSetup: {
        hiddenSelectionKeys: [
            QIDAHEN_SCENARIO_SETUP_FIELD,
            ...QIDAHEN_PREGAME_CHOICE_FIELDS.map((field) => field.key),
        ],
        forcedSelections: {
            [QIDAHEN_IN_MATCH_SCENARIO_VOTE_FIELD]: 'enabled',
        },
        showSetupOptions: false,
    },
    publicRoomSetupSummary: {
        scenario: {
            options: Object.fromEntries(
                QIDAHEN_SCENARIO_SETUP_OPTIONS.map((option) => [
                    option.value,
                    { labelKey: option.labelKey },
                ]),
            ),
        },
    },
    tags: ['card_driven', 'tactical'],
    bestPlayers: [3],
    ai: {
        capture: true,
        localAi: true,
        remoteAi: false,
    },
    criticalImages: [
        'qidahen/board/qidahen-main-map',
        'qidahen/cards/backs/ming-deck-back',
        'qidahen/cards/backs/korea-deck-back',
        'qidahen/cards/backs/qidahen-common-card-back',
        'qidahen/cards/atlases/ming-faction-deck-atlas',
        'qidahen/cards/atlases/mongol-faction-deck-atlas',
        'qidahen/cards/atlases/korea-special-deck-atlas',
        'qidahen/cards/atlases/ordinary-hand-atlas05',
        'qidahen/markers/ming-control-diplomacy-marker-a',
        'qidahen/markers/jin-control-diplomacy-marker-a',
        'qidahen/markers/chronology-year-marker',
        'qidahen/units/ming-regular-infantry-unit',
        'qidahen/units/ming-regular-cavalry-unit',
    ],
    warmImages: [
        'qidahen/cards/backs/mongol-deck-back',
        'qidahen/cards/backs/jin-deck-back',
        'qidahen/cards/atlases/jin-faction-deck-atlas',
        'qidahen/markers/mongol-control-diplomacy-marker-a',
        'qidahen/markers/ming-control-diplomacy-marker-b',
        'qidahen/markers/mongol-control-diplomacy-marker-b',
        'qidahen/markers/jin-control-diplomacy-marker-b',
        'qidahen/markers/drought-marker',
        'qidahen/markers/battle-defeat-marker',
        'qidahen/markers/ruin-marker',
        'qidahen/markers/hanseong-victory-point-marker',
        'qidahen/markers/imperial-seal-victory-point-marker',
        'qidahen/markers/ming-score-marker',
        'qidahen/markers/mongol-score-marker',
        'qidahen/markers/jin-score-marker',
        'qidahen/markers/jin-homeland-marker',
        'qidahen/markers/mongol-homeland-marker',
        'qidahen/units/ming-regular-artillery-unit',
        'qidahen/units/ming-mercenary-infantry-unit',
        'qidahen/units/ming-mercenary-cavalry-unit',
        'qidahen/units/ming-mercenary-artillery-unit',
        'qidahen/units/ming-chuanbing-unit',
        'qidahen/units/mongol-regular-infantry-unit',
        'qidahen/units/mongol-regular-cavalry-unit',
        'qidahen/units/mongol-regular-artillery-unit',
        'qidahen/units/mongol-mercenary-infantry-unit',
        'qidahen/units/mongol-mercenary-cavalry-unit',
        'qidahen/units/jin-regular-infantry-unit',
        'qidahen/units/jin-regular-cavalry-unit',
        'qidahen/units/jin-regular-artillery-unit',
        'qidahen/units/jin-mercenary-infantry-unit',
        'qidahen/units/jin-mercenary-cavalry-unit',
        'qidahen/units/neutral-infantry-unit',
        'qidahen/units/neutral-cavalry-unit',
    ],
    mobileProfile: 'landscape-adapted',
    preferredOrientation: 'landscape',
    mobileLayoutPreset: 'map-shell',
    mobileBattlefieldZoom: 'game-owned',
    shellTargets: ['pwa', 'app-webview', 'mini-program-webview'],
    pageShell: {
        tutorialCatalogTheme: {
            className: 'tutorial-catalog-stage--qidahen',
            chapterAccents: ['#d2b775', '#9f3426', '#ead7a7', '#c59152', '#b85b47', '#d2b775'],
        },
    },
    mobileDelivery: {
        mode: 'package-managed',
        runtimeChannel: 'stable',
        modulePackId: 'qidahen',
        assetPackId: 'qidahen',
    },
};

export const QIDAHEN_MANIFEST: GameManifestEntry = entry;

export default entry;
