/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameManifestEntry } from './manifest.types';

import entry0 from './airepoworkbench/manifest';
import entry1 from './archview/manifest';
import entry2 from './assetslicer/manifest';
import entry3 from './audiobrowser/manifest';
import entry4 from './cardia/manifest';
import entry5 from './dicethrone/manifest';
import entry6 from './fxpreview/manifest';
import entry7 from './smashup/manifest';
import entry8 from './splendor/manifest';
import entry9 from './summonerwars/manifest';
import entry10 from './tictactoe/manifest';
import entry11 from './ugcbuilder/manifest';

export const GAME_MANIFEST: GameManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
    entry5,
    entry6,
    entry7,
    entry8,
    entry9,
    entry10,
    entry11,
];

export const GAME_MANIFEST_BY_ID: Record<string, GameManifestEntry> = Object.fromEntries(
    GAME_MANIFEST.map((entry) => [entry.id, entry])
);
