/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameServerManifestEntry } from './manifest.server.types';

import manifest0 from './cardia/manifest';
import { engineConfig as engineConfig0 } from './cardia/game';
import manifest1 from './dicethrone/manifest';
import { engineConfig as engineConfig1 } from './dicethrone/game';
import manifest2 from './smashup/manifest';
import { engineConfig as engineConfig2 } from './smashup/game';
import manifest3 from './summonerwars/manifest';
import { engineConfig as engineConfig3 } from './summonerwars/game';
import manifest4 from './tictactoe/manifest';
import { engineConfig as engineConfig4 } from './tictactoe/game';

const entry0: GameServerManifestEntry = {
    manifest: manifest0,
    engineConfig: engineConfig0,
};

const entry1: GameServerManifestEntry = {
    manifest: manifest1,
    engineConfig: engineConfig1,
};

const entry2: GameServerManifestEntry = {
    manifest: manifest2,
    engineConfig: engineConfig2,
};

const entry3: GameServerManifestEntry = {
    manifest: manifest3,
    engineConfig: engineConfig3,
};

const entry4: GameServerManifestEntry = {
    manifest: manifest4,
    engineConfig: engineConfig4,
};

export const GAME_SERVER_MANIFEST: GameServerManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
];

export const GAME_SERVER_MANIFEST_BY_ID: Record<string, GameServerManifestEntry> = Object.fromEntries(
    GAME_SERVER_MANIFEST.map((entry) => [entry.manifest.id, entry])
);
