/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameClientManifestEntry, GameClientRuntimeModule } from './manifest.client.types';
import { ManifestGameThumbnail } from '../components/lobby/thumbnails';

import manifest0 from './betrayal/manifest';
import Thumbnail0 from './betrayal/thumbnail';

import manifest1 from './cardia/manifest';
import Thumbnail1 from './cardia/thumbnail';

import manifest2 from './dicethrone/manifest';
import Thumbnail2 from './dicethrone/thumbnail';

import manifest3 from './fantasyrealms/manifest';
import Thumbnail3 from './fantasyrealms/thumbnail';

import manifest4 from './qidahen/manifest';
import Thumbnail4 from './qidahen/thumbnail';

import manifest5 from './smashup/manifest';
import Thumbnail5 from './smashup/thumbnail';

import manifest6 from './splendor/manifest';
import Thumbnail6 from './splendor/thumbnail';

import manifest7 from './summonerwars/manifest';
import Thumbnail7 from './summonerwars/thumbnail';

import manifest8 from './tictactoe/manifest';
import Thumbnail8 from './tictactoe/thumbnail';

const loadRuntime0 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule] = await Promise.all([
        import('./betrayal/game'),
        import('./betrayal/Board'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
    };
};

const loadCriticalImageResolver0 = async () => {
    const resolverModule = await import('./betrayal/criticalImageResolver');
    return resolverModule.default ?? resolverModule.betrayalCriticalImageResolver;
};

const loadRuntime1 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule] = await Promise.all([
        import('./cardia/game'),
        import('./cardia/Board'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
    };
};

const loadTutorial1 = async () => {
    const tutorialModule = await import('./cardia/tutorial');
    return tutorialModule.default;
};

const loadCriticalImageResolver1 = async () => {
    const resolverModule = await import('./cardia/criticalImageResolver');
    return resolverModule.default ?? resolverModule.cardiaCriticalImageResolver;
};

const loadRuntime2 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, latencyModule, runtimeAdapterModule] = await Promise.all([
        import('./dicethrone/game'),
        import('./dicethrone/Board'),
        import('./dicethrone/latencyConfig'),
        import('./dicethrone/runtimeAdapter'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        latencyConfig: latencyModule.diceThroneLatencyConfig,
        runtimeAdapter: runtimeAdapterModule.diceThroneGameRuntimeAdapter,
    };
};

const loadTutorial2 = async () => {
    const tutorialModule = await import('./dicethrone/tutorial');
    return tutorialModule.default;
};

const loadCriticalImageResolver2 = async () => {
    const resolverModule = await import('./dicethrone/criticalImageResolver');
    return resolverModule.default ?? resolverModule.diceThroneCriticalImageResolver;
};

const loadRuntime3 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule] = await Promise.all([
        import('./fantasyrealms/game'),
        import('./fantasyrealms/Board'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
    };
};

const loadRuntime4 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule] = await Promise.all([
        import('./qidahen/game'),
        import('./qidahen/Board'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
    };
};

const loadCriticalImageResolver4 = async () => {
    const resolverModule = await import('./qidahen/criticalImageResolver');
    return resolverModule.default ?? resolverModule.qidahenCriticalImageResolver;
};

const loadRuntime5 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, latencyModule, runtimeAdapterModule] = await Promise.all([
        import('./smashup/game'),
        import('./smashup/Board'),
        import('./smashup/latencyConfig'),
        import('./smashup/runtimeAdapter'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        latencyConfig: latencyModule.smashUpLatencyConfig,
        runtimeAdapter: runtimeAdapterModule.smashUpGameRuntimeAdapter,
    };
};

const loadTutorial5 = async () => {
    const tutorialModule = await import('./smashup/tutorial');
    return tutorialModule.default;
};

const loadCriticalImageResolver5 = async () => {
    const resolverModule = await import('./smashup/criticalImageResolver');
    return resolverModule.default;
};

const loadRuntime6 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule] = await Promise.all([
        import('./splendor/game'),
        import('./splendor/Board'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
    };
};

const loadTutorial6 = async () => {
    const tutorialModule = await import('./splendor/tutorial');
    return tutorialModule.default;
};

const loadCriticalImageResolver6 = async () => {
    const resolverModule = await import('./splendor/criticalImageResolver');
    return resolverModule.default ?? resolverModule.splendorCriticalImageResolver;
};

const loadRuntime7 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, latencyModule, runtimeAdapterModule] = await Promise.all([
        import('./summonerwars/game'),
        import('./summonerwars/Board'),
        import('./summonerwars/latencyConfig'),
        import('./summonerwars/runtimeAdapter'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        latencyConfig: latencyModule.summonerWarsLatencyConfig,
        runtimeAdapter: runtimeAdapterModule.summonerWarsGameRuntimeAdapter,
    };
};

const loadTutorial7 = async () => {
    const tutorialModule = await import('./summonerwars/tutorial');
    return tutorialModule.default;
};

const loadCriticalImageResolver7 = async () => {
    const resolverModule = await import('./summonerwars/criticalImageResolver');
    return resolverModule.default ?? resolverModule.summonerWarsCriticalImageResolver;
};

const loadRuntime8 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, latencyModule] = await Promise.all([
        import('./tictactoe/game'),
        import('./tictactoe/Board'),
        import('./tictactoe/latencyConfig'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        latencyConfig: latencyModule.ticTacToeLatencyConfig,
    };
};

const loadTutorial8 = async () => {
    const tutorialModule = await import('./tictactoe/tutorial');
    return tutorialModule.default;
};

const entry0: GameClientManifestEntry = {
    manifest: manifest0,
    thumbnail: <Thumbnail0 />,
    loadRuntime: loadRuntime0,
    loadCriticalImageResolver: loadCriticalImageResolver0,
};

const entry1: GameClientManifestEntry = {
    manifest: manifest1,
    thumbnail: <Thumbnail1 />,
    loadRuntime: loadRuntime1,
    loadTutorial: loadTutorial1,
    loadCriticalImageResolver: loadCriticalImageResolver1,
};

const entry2: GameClientManifestEntry = {
    manifest: manifest2,
    thumbnail: <Thumbnail2 />,
    loadRuntime: loadRuntime2,
    loadTutorial: loadTutorial2,
    loadCriticalImageResolver: loadCriticalImageResolver2,
};

const entry3: GameClientManifestEntry = {
    manifest: manifest3,
    thumbnail: <Thumbnail3 />,
    loadRuntime: loadRuntime3,
};

const entry4: GameClientManifestEntry = {
    manifest: manifest4,
    thumbnail: <Thumbnail4 />,
    loadRuntime: loadRuntime4,
    loadCriticalImageResolver: loadCriticalImageResolver4,
};

const entry5: GameClientManifestEntry = {
    manifest: manifest5,
    thumbnail: <Thumbnail5 />,
    loadRuntime: loadRuntime5,
    loadTutorial: loadTutorial5,
    loadCriticalImageResolver: loadCriticalImageResolver5,
};

const entry6: GameClientManifestEntry = {
    manifest: manifest6,
    thumbnail: <Thumbnail6 />,
    loadRuntime: loadRuntime6,
    loadTutorial: loadTutorial6,
    loadCriticalImageResolver: loadCriticalImageResolver6,
};

const entry7: GameClientManifestEntry = {
    manifest: manifest7,
    thumbnail: <Thumbnail7 />,
    loadRuntime: loadRuntime7,
    loadTutorial: loadTutorial7,
    loadCriticalImageResolver: loadCriticalImageResolver7,
};

const entry8: GameClientManifestEntry = {
    manifest: manifest8,
    thumbnail: <Thumbnail8 />,
    loadRuntime: loadRuntime8,
    loadTutorial: loadTutorial8,
};

export const GAME_CLIENT_MANIFEST: GameClientManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
    entry5,
    entry6,
    entry7,
    entry8,
];

export const GAME_CLIENT_MANIFEST_BY_ID: Record<string, GameClientManifestEntry> = Object.fromEntries(
    GAME_CLIENT_MANIFEST.map((entry) => [entry.manifest.id, entry])
);
