export type {
    GameCategory,
    GameManifestAiSupport,
    GameManifestEntry,
    GameManifestMobileDelivery,
    GameStatusTag,
    GameManifestType,
    GameMobileBattlefieldZoom,
    GameMobileDeliveryMode,
    GameMobileLayoutPreset,
    GameMobileProfile,
    GameOrientationPreference,
    GamePreloadAssets,
    GameSetupField,
    GameSetupMultiSelectField,
    GameSetupSelectField,
    GameSetupSelectOption,
    GameShellTarget,
} from '../shared/gameManifest.types';
