/* eslint-disable */
// AUTO-GENERATED by scripts/generate_game_manifests.js. DO NOT EDIT.
import type { GameClientManifestEntry } from './manifest.client.types';
import { ManifestGameThumbnail } from '../components/lobby/thumbnails';

import manifest0 from './assetslicer/manifest';

import manifest1 from './dicethrone/manifest';
import Game1 from './dicethrone/game';
import Board1 from './dicethrone/Board';
import Tutorial1 from './dicethrone/tutorial';
import Thumbnail1 from './dicethrone/thumbnail';

import manifest2 from './smashup/manifest';
import Game2 from './smashup/game';
import Board2 from './smashup/Board';
import Tutorial2 from './smashup/tutorial';
import Thumbnail2 from './smashup/thumbnail';

import manifest3 from './summonerwars/manifest';
import Game3 from './summonerwars/game';
import Board3 from './summonerwars/Board';
import Tutorial3 from './summonerwars/tutorial';
import Thumbnail3 from './summonerwars/thumbnail';

import manifest4 from './tictactoe/manifest';
import Game4 from './tictactoe/game';
import Board4 from './tictactoe/Board';
import Tutorial4 from './tictactoe/tutorial';
import Thumbnail4 from './tictactoe/thumbnail';

import manifest5 from './ugcbuilder/manifest';

const entry0: GameClientManifestEntry = {
    manifest: manifest0,
    thumbnail: <ManifestGameThumbnail manifest={manifest0} />,
};

const entry1: GameClientManifestEntry = {
    manifest: manifest1,
    game: Game1,
    board: Board1,
    tutorial: Tutorial1,
    thumbnail: <Thumbnail1 />,
};

const entry2: GameClientManifestEntry = {
    manifest: manifest2,
    game: Game2,
    board: Board2,
    tutorial: Tutorial2,
    thumbnail: <Thumbnail2 />,
};

const entry3: GameClientManifestEntry = {
    manifest: manifest3,
    game: Game3,
    board: Board3,
    tutorial: Tutorial3,
    thumbnail: <Thumbnail3 />,
};

const entry4: GameClientManifestEntry = {
    manifest: manifest4,
    game: Game4,
    board: Board4,
    tutorial: Tutorial4,
    thumbnail: <Thumbnail4 />,
};

const entry5: GameClientManifestEntry = {
    manifest: manifest5,
    thumbnail: <ManifestGameThumbnail manifest={manifest5} />,
};

export const GAME_CLIENT_MANIFEST: GameClientManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
    entry5,
];

export const GAME_CLIENT_MANIFEST_BY_ID: Record<string, GameClientManifestEntry> = Object.fromEntries(
    GAME_CLIENT_MANIFEST.map((entry) => [entry.manifest.id, entry])
);
