/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameManifestEntry } from './manifest.types';

import entry0 from './archview/manifest';
import entry1 from './assetslicer/manifest';
import entry2 from './audiobrowser/manifest';
import entry3 from './cardia/manifest';
import entry4 from './dicethrone/manifest';
import entry5 from './fxpreview/manifest';
import entry6 from './smashup/manifest';
import entry7 from './summonerwars/manifest';
import entry8 from './tictactoe/manifest';
import entry9 from './ugcbuilder/manifest';

export const GAME_MANIFEST: GameManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
    entry5,
    entry6,
    entry7,
    entry8,
    entry9,
];

export const GAME_MANIFEST_BY_ID: Record<string, GameManifestEntry> = Object.fromEntries(
    GAME_MANIFEST.map((entry) => [entry.id, entry])
);
