import type { QidahenArmamentId, QidahenHandCard } from './types';

type QidahenAtlas05OrdinaryHandCardKind = Extract<
    NonNullable<QidahenHandCard['cardKind']>,
    'event' | 'armament' | 'tactic' | 'silver'
>;

export interface QidahenAtlas05OrdinaryHandCardIdentity {
    atlasIndex: number;
    cardId: number;
    cardDefId: string;
    displayName: string;
    cardKind: QidahenAtlas05OrdinaryHandCardKind;
    armamentId: QidahenArmamentId | null;
}

export const QIDAHEN_ATLAS05_ORDINARY_HAND_CARD_IDENTITIES = [
    {
        atlasIndex: 0,
        cardId: 1600,
        cardDefId: 'qidahen-atlas05-1600-counter-spy-plot',
        displayName: '反间计',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 1,
        cardId: 1601,
        cardDefId: 'qidahen-atlas05-1601-defeat-in-detail',
        displayName: '各个击破',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 2,
        cardId: 1602,
        cardDefId: 'qidahen-atlas05-1602-bayara',
        displayName: '巴雅喇',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 3,
        cardId: 1603,
        cardDefId: 'qidahen-atlas05-1603-infantry-armor',
        displayName: '步兵铁甲',
        cardKind: 'armament',
        armamentId: 'infantry-armor',
    },
    {
        atlasIndex: 4,
        cardId: 1604,
        cardDefId: 'qidahen-atlas05-1604-instigate-defection-insider',
        displayName: '策反/内应',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 5,
        cardId: 1605,
        cardDefId: 'qidahen-atlas05-1605-establish-han-banners',
        displayName: '成立汉八旗',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 6,
        cardId: 1606,
        cardDefId: 'qidahen-atlas05-1606-establish-manzhou-banners',
        displayName: '成立满八旗',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 7,
        cardId: 1607,
        cardDefId: 'qidahen-atlas05-1607-establish-mongol-banners',
        displayName: '成立蒙八旗',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 8,
        cardId: 1608,
        cardDefId: 'qidahen-atlas05-1608-mongol-drought',
        displayName: '蒙古大旱',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 9,
        cardId: 1609,
        cardDefId: 'qidahen-atlas05-1609-seven-grievances',
        displayName: '七大恨',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 10,
        cardId: 1610,
        cardDefId: 'qidahen-atlas05-1610-cavalry-armor',
        displayName: '骑兵铁甲',
        cardKind: 'armament',
        armamentId: 'cavalry-armor',
    },
    {
        atlasIndex: 11,
        cardId: 1611,
        cardDefId: 'qidahen-atlas05-1611-instigate-defection',
        displayName: '策反',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 12,
        cardId: 1612,
        cardDefId: 'qidahen-atlas05-1612-raid-grain',
        displayName: '打草惊蛇',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 13,
        cardId: 1613,
        cardDefId: 'qidahen-atlas05-1613-northeast-drought',
        displayName: '东北大旱',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 14,
        cardId: 1614,
        cardDefId: 'qidahen-atlas05-1614-cross-mountains',
        displayName: '翻山越岭',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 15,
        cardId: 1615,
        cardDefId: 'qidahen-atlas05-1615-arrows-like-rain',
        displayName: '箭如雨下',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 16,
        cardId: 1616,
        cardDefId: 'qidahen-atlas05-1616-fine-steel-saber',
        displayName: '精钢马刀',
        cardKind: 'armament',
        armamentId: 'cavalry-firearm',
    },
    {
        atlasIndex: 17,
        cardId: 1617,
        cardDefId: 'qidahen-atlas05-1617-horse-breeding',
        displayName: '骏马育种',
        cardKind: 'armament',
        armamentId: 'horse-breeding',
    },
    {
        atlasIndex: 18,
        cardId: 1618,
        cardDefId: 'qidahen-atlas05-1618-cavalry-charge',
        displayName: '骑兵冲锋',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 19,
        cardId: 1619,
        cardDefId: 'qidahen-atlas05-1619-cavalry-armor-alt',
        displayName: '骑兵铁甲',
        cardKind: 'armament',
        armamentId: 'cavalry-armor',
    },
    {
        atlasIndex: 20,
        cardId: 1620,
        cardDefId: 'qidahen-atlas05-1620-mounted-infantry',
        displayName: '骑马步兵',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 21,
        cardId: 1621,
        cardDefId: 'qidahen-atlas05-1621-power-struggle-coup',
        displayName: '开门迎降',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 22,
        cardId: 1622,
        cardDefId: 'qidahen-atlas05-1622-raid-and-ambush',
        displayName: '偷袭与伏击',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 23,
        cardId: 1623,
        cardDefId: 'qidahen-atlas05-1623-mongol-nobles-congress',
        displayName: '王公大会',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 24,
        cardId: 1624,
        cardDefId: 'qidahen-atlas05-1624-silver',
        displayName: '银两',
        cardKind: 'silver',
        armamentId: null,
    },
    {
        atlasIndex: 25,
        cardId: 1625,
        cardDefId: 'qidahen-atlas05-1625-jade-casket-unearthed',
        displayName: '玉匣出土',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 26,
        cardId: 1626,
        cardDefId: 'qidahen-atlas05-1626-artillery-tech',
        displayName: '火炮技术',
        cardKind: 'armament',
        armamentId: 'artillery-tech',
    },
    {
        atlasIndex: 27,
        cardId: 1627,
        cardDefId: 'qidahen-atlas05-1627-infantry-armor-alt',
        displayName: '步兵铁甲',
        cardKind: 'armament',
        armamentId: 'infantry-armor',
    },
    {
        atlasIndex: 28,
        cardId: 1628,
        cardDefId: 'qidahen-atlas05-1628-infantry-cavalry-combined',
        displayName: '步骑联合',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 29,
        cardId: 1629,
        cardDefId: 'qidahen-atlas05-1629-instigate-defection-alt',
        displayName: '策反',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 30,
        cardId: 1630,
        cardDefId: 'qidahen-atlas05-1630-ginseng-and-sable',
        displayName: '人参貂皮',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 31,
        cardId: 1631,
        cardDefId: 'qidahen-atlas05-1631-northeast-army',
        displayName: '东北大军',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 32,
        cardId: 1632,
        cardDefId: 'qidahen-atlas05-1632-pincer-advance',
        displayName: '分进合击',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 33,
        cardId: 1633,
        cardDefId: 'qidahen-atlas05-1633-tribute-edict',
        displayName: '封贡敕书',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 34,
        cardId: 1634,
        cardDefId: 'qidahen-atlas05-1634-red-coat-cannon',
        displayName: '红衣大炮',
        cardKind: 'armament',
        armamentId: 'artillery-tech',
    },
    {
        atlasIndex: 35,
        cardId: 1635,
        cardDefId: 'qidahen-atlas05-1635-steadfast-defense',
        displayName: '坚守不屈',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 36,
        cardId: 1636,
        cardDefId: 'qidahen-atlas05-1636-cheval-de-frise',
        displayName: '拒马',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 37,
        cardId: 1637,
        cardDefId: 'qidahen-atlas05-1637-mongol-drought-alt',
        displayName: '蒙古大旱',
        cardKind: 'event',
        armamentId: null,
    },
    {
        atlasIndex: 38,
        cardId: 1638,
        cardDefId: 'qidahen-atlas05-1638-chain-cannon-formation',
        displayName: '链炮阵',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 39,
        cardId: 1639,
        cardDefId: 'qidahen-atlas05-1639-cavalry-firearm',
        displayName: '骑兵火器',
        cardKind: 'armament',
        armamentId: 'cavalry-firearm',
    },
    {
        atlasIndex: 40,
        cardId: 1640,
        cardDefId: 'qidahen-atlas05-1640-jirinai-infantry',
        displayName: '机里耐步兵',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 41,
        cardId: 1641,
        cardDefId: 'qidahen-atlas05-1641-cavalry-armor-third',
        displayName: '骑兵铁甲',
        cardKind: 'armament',
        armamentId: 'cavalry-armor',
    },
    {
        atlasIndex: 42,
        cardId: 1642,
        cardDefId: 'qidahen-atlas05-1642-western-bastion',
        displayName: '西式棱堡',
        cardKind: 'armament',
        armamentId: 'western-bastion',
    },
    {
        atlasIndex: 43,
        cardId: 1643,
        cardDefId: 'qidahen-atlas05-1643-silver',
        displayName: '银两',
        cardKind: 'silver',
        armamentId: null,
    },
    {
        atlasIndex: 44,
        cardId: 1644,
        cardDefId: 'qidahen-atlas05-1644-wuzhen-chaoha',
        displayName: '鸟真超哈',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 45,
        cardId: 1645,
        cardDefId: 'qidahen-atlas05-1645-war-chariot-formation',
        displayName: '战车阵',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 46,
        cardId: 1646,
        cardDefId: 'qidahen-atlas05-1646-linked-muskets',
        displayName: '连环火铳',
        cardKind: 'armament',
        armamentId: 'long-barreled-musket',
    },
    {
        atlasIndex: 50,
        cardId: 1650,
        cardDefId: 'qidahen-atlas05-1650-wuzhen-chaoha-special',
        displayName: '乌真超哈',
        cardKind: 'tactic',
        armamentId: null,
    },
    {
        atlasIndex: 60,
        cardId: 1660,
        cardDefId: 'qidahen-atlas05-1660-feigned-retreat-lure-enemy',
        displayName: '诈败诱敌',
        cardKind: 'tactic',
        armamentId: null,
    },
] as const satisfies readonly QidahenAtlas05OrdinaryHandCardIdentity[];

export const QIDAHEN_ATLAS05_ORDINARY_HAND_CARD_IDENTITY_BY_INDEX: ReadonlyMap<
    number,
    QidahenAtlas05OrdinaryHandCardIdentity
> = new Map(
    QIDAHEN_ATLAS05_ORDINARY_HAND_CARD_IDENTITIES.map((identity) => [identity.atlasIndex, identity]),
);

export const QIDAHEN_ATLAS05_ORDINARY_HAND_CARD_RULES_SUMMARY_BY_DEF_ID = {
    'qidahen-atlas05-1600-counter-spy-plot': '弃 2 张手牌，指定并移除一张对手场上的人物牌；不能对努尔哈赤、林丹汗、阿巴凯使用；使用后移出游戏。',
    'qidahen-atlas05-1601-defeat-in-detail': '只能在遭到攻击时打出；敌方来自不同边界的部队需分别进行完整战斗；由防守方决定结算顺序；大明、蒙古使用无效果。',
    'qidahen-atlas05-1602-bayara': '甲兵防守用：战斗中己方步兵防御等级 +1；锁链甲进攻用：战斗中敌方所有部队防御等级 -1。',
    'qidahen-atlas05-1603-infantry-armor': '步兵部队防御等级 +1，原始值为 3。',
    'qidahen-atlas05-1604-instigate-defection-insider': '只能在有敌方火炮部队参战时使用；敌方 1 个火炮部队临时改变成我方阵营并立即用于战斗。',
    'qidahen-atlas05-1605-establish-han-banners': '持续事件；当前每个控制的汉人区域可立即建立 1 个等级 2 次级部队，之后控制的汉人区域视为本土；大明、蒙古使用无效果。',
    'qidahen-atlas05-1606-establish-manzhou-banners': '持续事件；当前每个控制的女真人区域可立即建立 1 个等级 2 次级部队，之后控制的女真人区域视为本土；大明、蒙古使用无效果。',
    'qidahen-atlas05-1607-establish-mongol-banners': '持续事件；当前每个后金控制、除察哈尔部外的蒙古人区域可立即建立 1 个等级 2 次级部队，相关区域视为本土；大明、蒙古使用无效果。',
    'qidahen-atlas05-1608-mongol-drought': '在一个蒙古人区域放置旱灾标记；使用后移出游戏；轮盘行动标记进入下半年后不能使用。',
    'qidahen-atlas05-1609-seven-grievances': '效果 8；在任意本土区域建立总共 2 个等级 3 的主力步兵部队；若已打出“成立满州（蒙古、汉军）八旗”，每 1 张可多建立 1 个等级 3 的主力步兵部队；使用后移出游戏。大明、蒙古使用无效果。',
    'qidahen-atlas05-1610-cavalry-armor': '骑兵部队防御等级 +1，原始值为 3。',
    'qidahen-atlas05-1611-instigate-defection': '只能在有敌方火炮部队参战时使用；敌方 1 个火炮部队临时改变成我方阵营并参战。',
    'qidahen-atlas05-1612-raid-grain': '扎营过程中，交战劫掠的对手不会受到伤害。',
    'qidahen-atlas05-1613-northeast-drought': '在一个女真人区域放置旱灾标记；使用后移出游戏；轮盘行动标记进入下半年后不能使用。',
    'qidahen-atlas05-1614-cross-mountains': '执行一次进攻行动；本次进攻中，长城、山脉边界视为平原边界。',
    'qidahen-atlas05-1615-arrows-like-rain': '野战步兵阶段使用；我方结算掷骰后，对手才能结算掷骰；无效对手“拒马”效果。',
    'qidahen-atlas05-1616-fine-steel-saber': '骑兵部队掷骰数 +1；必须控制骥尔多斯部才能使用上述效果。',
    'qidahen-atlas05-1617-horse-breeding': '骑兵部队移动力 +1。',
    'qidahen-atlas05-1618-cavalry-charge': '野战时才能使用，每个骑兵部队掷骰数 +2。',
    'qidahen-atlas05-1619-cavalry-armor-alt': '骑兵部队防御等级 +1，原始值为 3。',
    'qidahen-atlas05-1620-mounted-infantry': '此战我方附兵部队视为步兵部队，包含防御等级计算、战术适用与攻击等级骰。',
    'qidahen-atlas05-1621-power-struggle-coup': '第一项、第二项可都执行或择一执行：后金可弃掉任意数量在场人物，然后每剩余 1 个后金在场人物必须弃掉 2 个部队；大明选择一个派系，弃掉该派系全部在场人物；后金、大明使用效果相同；使用后移出游戏。',
    'qidahen-atlas05-1622-raid-and-ambush': '敌人增援时可指定一种兵种骰子等级 -1；可再从手牌追加一张战术牌。',
    'qidahen-atlas05-1623-mongol-nobles-congress': '执行两项效果之一：打出任意蒙古人物，或将已登场的大明/后金任意蒙古人物拿回蒙古人物牌堆；后金、大明使用无效果。',
    'qidahen-atlas05-1624-silver': '银两资源牌；不能作为独立行动入口，只能作为支付或资源弃牌候选。',
    'qidahen-atlas05-1625-jade-casket-unearthed': '持续事件；若拥有者同时控制归化城和鄂尔多斯部，视为获得 1 点胜利分数；失去任一区域时此牌转移给占领该区域的玩家。',
    'qidahen-atlas05-1626-artillery-tech': '炮兵可训练等级 +1，原始值为 0；每个炮兵战斗掷骰数 +1；后金、蒙古可选择同上或建立 1 个 Lv1 炮兵。',
    'qidahen-atlas05-1627-infantry-armor-alt': '步兵部队防御等级 +1，原始值为 3。',
    'qidahen-atlas05-1628-infantry-cavalry-combined': '不能在攻城、守城时使用；我方骑兵在步兵攻击阶段可撤离；步兵攻击阶段若骑兵和步兵一同攻击，步兵、骑兵骰子等级 +1；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1629-instigate-defection-alt': '敌方次级部队参战时使用，使 1 个敌方次级部队改为己方阵营并参战；战后按牌面回归。',
    'qidahen-atlas05-1630-ginseng-and-sable': '指定 1 个对手，获得他的 1 张手牌，由该对手选择给出哪张手牌；使用后将此牌放入该对手弃牌堆；大明、蒙古使用无效果。',
    'qidahen-atlas05-1631-northeast-army': '在一个女真人区域放置甲喇标记；使用后移出游戏；撤退行动标记走到新年时不能使用；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1632-pincer-advance': '只能于野战时使用；可以再移动最多 2 个没有参战的部队进入战斗；进入战场的部队仍受行动距离限制。',
    'qidahen-atlas05-1633-tribute-edict': '弃 1 张手牌后指定 1 个对手执行 1 次“赐印招安”或“驱虎吞狼”行动，并将此牌放入该对手弃牌堆；后金、蒙古弃牌时公开，视作 2 张“银两”牌。',
    'qidahen-atlas05-1634-red-coat-cannon': '野战防守时炮兵部队掷骰数 +1；攻城进攻时炮兵部队掷骰数 +2；后金、蒙古使用无效果。',
    'qidahen-atlas05-1635-steadfast-defense': '只能于守城时使用；对手本次攻城掷骰结果除以 2，先计算骰点加减，最后再除以 2，小数无条件舍去；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1636-cheval-de-frise': '只能于野战时使用；使对方骑兵没有在步兵阶段掷骰，并使先发动的对手“箭如雨下”无效；遇后发动的“箭如雨下”时本牌无效；若同时发动双方技能则两者均可生效；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1637-mongol-drought-alt': '在一个蒙古人区域放置旱灾标记；使用后移出游戏；轮盘行动标记进入下半年后不能使用；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1638-chain-cannon-formation': '不能在攻城、守城时使用；战斗中承受损伤时，一律由炮兵单位先承受；每个炮兵的防御等级为 4，受损炮兵立即移除；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1639-cavalry-firearm': '野战骑兵阶段先结算我方掷骰，对手再结算掷骰；使用拒马后无效；骑兵掷骰数 +1；后金、蒙古使用无效果。',
    'qidahen-atlas05-1640-jirinai-infantry': '能射军防守用：防守明军中步兵部队掷骰时我方先结算；聚刀军进攻用：进攻明军中己方步兵部队掷骰数 +1。',
    'qidahen-atlas05-1641-cavalry-armor-third': '骑兵部队防御等级 +1，原始值为 3；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1642-western-bastion': '守城战斗时每个部队可投 2 颗骰子；后金、蒙古使用无效果。',
    'qidahen-atlas05-1643-silver': '银两资源牌；不能作为独立行动入口，只能作为支付或资源弃牌候选。',
    'qidahen-atlas05-1644-wuzhen-chaoha': '不能在攻城、守城时使用；战斗中我方步兵骰子等级 +1；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1645-war-chariot-formation': '本次战斗中步兵部队防御等级 +1；后金、蒙古使用效果同上。',
    'qidahen-atlas05-1646-linked-muskets': '野战步兵阶段敌方结算掷骰时我方先结算；使用拒马、步骑联合后无效；步兵部队掷骰数 +1；后金、蒙古使用无效果。',
    'qidahen-atlas05-1650-wuzhen-chaoha-special': '效果 8；指定 1 个步兵部队，使其提前在炮兵阶段进行攻击；每所毁 1 张「火炮技术」，这个被指定的步兵部队攻击等级 +1；该部队仍可以享受其他步兵部队加成，可以承受伤害。大明、蒙古使用效果同上。',
    'qidahen-atlas05-1660-feigned-retreat-lure-enemy': '效果 8；取消对手宣告的骑兵劫掠，敌方骑兵直接投入战斗并照常撤退。大明、蒙古使用效果同上。',
} as const satisfies Record<
    typeof QIDAHEN_ATLAS05_ORDINARY_HAND_CARD_IDENTITIES[number]['cardDefId'],
    string
>;
