import type { TutorialManifest } from '../../engine/types';
import { THE_GANG_COMMANDS, THE_GANG_EVENTS } from './domain/types';

export const TheGangTutorial: TutorialManifest = {
    id: 'the-gang-basic',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'intro',
            content: 'game-the-gang:tutorial.steps.intro',
            highlightTarget: 'the-gang-title',
            position: 'bottom',
            infoStep: true,
            showMask: true,
            viewAs: '0',
        },
        {
            id: 'goal-track',
            content: 'game-the-gang:tutorial.steps.goalTrack',
            highlightTarget: 'the-gang-score-track',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'hand',
            content: 'game-the-gang:tutorial.steps.hand',
            highlightTarget: 'the-gang-hand',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'hand-rank-reference',
            content: 'game-the-gang:tutorial.steps.handRankReference',
            highlightTarget: 'the-gang-hand-rank-reference',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'chip-choice',
            content: 'game-the-gang:tutorial.steps.chipChoice',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'table-response',
            content: 'game-the-gang:tutorial.steps.tableResponse',
            highlightTarget: 'the-gang-player-list',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
        },
        {
            id: 'advance-round',
            content: 'game-the-gang:tutorial.steps.advanceRound',
            highlightTarget: 'the-gang-next-round',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.END_ROUND],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.ROUND_ENDED }],
        },
        {
            id: 'community-cards',
            content: 'game-the-gang:tutorial.steps.communityCards',
            highlightTarget: 'the-gang-round-panel',
            position: 'bottom',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'yellow-chip',
            content: 'game-the-gang:tutorial.steps.yellowChip',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'yellow-response',
            content: 'game-the-gang:tutorial.steps.yellowResponse',
            highlightTarget: 'the-gang-player-list',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
        },
        {
            id: 'turn-round',
            content: 'game-the-gang:tutorial.steps.turnRound',
            highlightTarget: 'the-gang-next-round',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.END_ROUND],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.ROUND_ENDED }],
        },
        {
            id: 'turn-card',
            content: 'game-the-gang:tutorial.steps.turnCard',
            highlightTarget: 'the-gang-round-panel',
            position: 'bottom',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'orange-chip',
            content: 'game-the-gang:tutorial.steps.orangeChip',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'orange-response',
            content: 'game-the-gang:tutorial.steps.orangeResponse',
            highlightTarget: 'the-gang-player-list',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
        },
        {
            id: 'river-round',
            content: 'game-the-gang:tutorial.steps.riverRound',
            highlightTarget: 'the-gang-next-round',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.END_ROUND],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.ROUND_ENDED }],
        },
        {
            id: 'final-chip',
            content: 'game-the-gang:tutorial.steps.finalChip',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'final-response',
            content: 'game-the-gang:tutorial.steps.finalResponse',
            highlightTarget: 'the-gang-player-list',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
        },
        {
            id: 'reveal-showdown',
            content: 'game-the-gang:tutorial.steps.revealShowdown',
            highlightTarget: 'the-gang-reveal-showdown',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.REVEAL_SHOWDOWN],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.SHOWDOWN_REVEALED }],
        },
        {
            id: 'showdown',
            content: 'game-the-gang:tutorial.steps.showdown',
            highlightTarget: 'the-gang-showdown-result',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'showdown-reading',
            content: 'game-the-gang:tutorial.steps.showdownReading',
            highlightTarget: 'the-gang-showdown-best-cards',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'finish',
            content: 'game-the-gang:tutorial.steps.finish',
            highlightTarget: 'the-gang-title',
            position: 'bottom',
            infoStep: true,
            showMask: true,
            viewAs: '0',
        },
    ],
};

export default TheGangTutorial;
