import type { TutorialAiAction, TutorialManifest } from '../../engine/types';
import { THE_GANG_COMMANDS, THE_GANG_EVENTS } from './domain/types';

const takeLowestAvailableChipAction = (playerId: string): TutorialAiAction => ({
    commandType: THE_GANG_COMMANDS.TAKE_CHIP,
    playerId,
    payload: {
        chip: 1,
        tutorialChipMode: 'lowest-unoccupied',
        tutorialOnlyIfMissing: true,
    },
});

const progressAction = (
    playerId: string,
    commandType: typeof THE_GANG_COMMANDS.END_ROUND | typeof THE_GANG_COMMANDS.REVEAL_SHOWDOWN,
): TutorialAiAction => ({
    commandType,
    playerId,
    payload: {},
});

const AI_RESPONSE_CHIP_ACTIONS: TutorialAiAction[] = [
    takeLowestAvailableChipAction('1'),
    takeLowestAvailableChipAction('2'),
];

const AI_END_ROUND_APPROVALS: TutorialAiAction[] = [
    progressAction('1', THE_GANG_COMMANDS.END_ROUND),
    progressAction('2', THE_GANG_COMMANDS.END_ROUND),
];

const AI_REVEAL_SHOWDOWN_APPROVALS: TutorialAiAction[] = [
    progressAction('1', THE_GANG_COMMANDS.REVEAL_SHOWDOWN),
    progressAction('2', THE_GANG_COMMANDS.REVEAL_SHOWDOWN),
];

export const TheGangTutorial: TutorialManifest = {
    id: 'the-gang-basic',
    numPlayers: 3,
    allowManualSkip: true,
    steps: [
        {
            id: 'intro',
            content: 'game-the-gang:tutorial.steps.intro',
            highlightTarget: 'the-gang-title',
            position: 'bottom',
            infoStep: true,
            showMask: true,
            viewAs: '0',
        },
        {
            id: 'goal-track',
            content: 'game-the-gang:tutorial.steps.goalTrack',
            highlightTarget: 'the-gang-score-track',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'hand',
            content: 'game-the-gang:tutorial.steps.hand',
            highlightTarget: 'the-gang-hand',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'hand-rank-reference',
            content: 'game-the-gang:tutorial.steps.handRankReference',
            highlightTarget: 'the-gang-hand-rank-reference',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'start-heist',
            content: 'game-the-gang:tutorial.steps.startHeist',
            highlightTarget: 'the-gang-start-heist',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.START_HEIST],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.HEIST_STARTED }],
        },
        {
            id: 'chip-choice',
            content: 'game-the-gang:tutorial.steps.chipChoice',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'table-response',
            content: 'game-the-gang:tutorial.steps.tableResponse',
            highlightTarget: 'the-gang-opponent-state',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            aiActions: AI_RESPONSE_CHIP_ACTIONS,
            autoAdvanceAfterAi: false,
        },
        {
            id: 'take-player-chip',
            content: 'game-the-gang:tutorial.steps.takePlayerChip',
            highlightTarget: 'the-gang-opponent-state',
            position: 'left',
            viewAs: '0',
            requireAction: true,
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'advance-round',
            content: 'game-the-gang:tutorial.steps.advanceRound',
            highlightTarget: 'the-gang-next-round',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.END_ROUND],
            aiActions: [
                takeLowestAvailableChipAction('1'),
                takeLowestAvailableChipAction('2'),
                ...AI_END_ROUND_APPROVALS,
            ],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.ROUND_ENDED }],
        },
        {
            id: 'community-cards',
            content: 'game-the-gang:tutorial.steps.communityCards',
            highlightTarget: 'the-gang-round-panel',
            position: 'bottom',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'yellow-chip',
            content: 'game-the-gang:tutorial.steps.yellowChip',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'yellow-response',
            content: 'game-the-gang:tutorial.steps.yellowResponse',
            highlightTarget: 'the-gang-opponent-state',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            aiActions: AI_RESPONSE_CHIP_ACTIONS,
            autoAdvanceAfterAi: false,
        },
        {
            id: 'turn-round',
            content: 'game-the-gang:tutorial.steps.turnRound',
            highlightTarget: 'the-gang-next-round',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.END_ROUND],
            aiActions: AI_END_ROUND_APPROVALS,
            advanceOnEvents: [{ type: THE_GANG_EVENTS.ROUND_ENDED }],
        },
        {
            id: 'turn-card',
            content: 'game-the-gang:tutorial.steps.turnCard',
            highlightTarget: 'the-gang-round-panel',
            position: 'bottom',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'orange-chip',
            content: 'game-the-gang:tutorial.steps.orangeChip',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'orange-response',
            content: 'game-the-gang:tutorial.steps.orangeResponse',
            highlightTarget: 'the-gang-opponent-state',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            aiActions: AI_RESPONSE_CHIP_ACTIONS,
            autoAdvanceAfterAi: false,
        },
        {
            id: 'river-round',
            content: 'game-the-gang:tutorial.steps.riverRound',
            highlightTarget: 'the-gang-next-round',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.END_ROUND],
            aiActions: AI_END_ROUND_APPROVALS,
            advanceOnEvents: [{ type: THE_GANG_EVENTS.ROUND_ENDED }],
        },
        {
            id: 'final-chip',
            content: 'game-the-gang:tutorial.steps.finalChip',
            highlightTarget: 'the-gang-chip-row',
            position: 'top',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            advanceOnEvents: [{ type: THE_GANG_EVENTS.CHIP_TAKEN, match: { playerId: '0' } }],
        },
        {
            id: 'final-response',
            content: 'game-the-gang:tutorial.steps.finalResponse',
            highlightTarget: 'the-gang-opponent-state',
            position: 'left',
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP],
            aiActions: AI_RESPONSE_CHIP_ACTIONS,
            autoAdvanceAfterAi: false,
        },
        {
            id: 'reveal-showdown',
            content: 'game-the-gang:tutorial.steps.revealShowdown',
            highlightTarget: 'the-gang-reveal-showdown',
            position: 'left',
            requireAction: true,
            viewAs: '0',
            allowedCommands: [THE_GANG_COMMANDS.TAKE_CHIP, THE_GANG_COMMANDS.REVEAL_SHOWDOWN],
            aiActions: AI_REVEAL_SHOWDOWN_APPROVALS,
            advanceOnEvents: [{ type: THE_GANG_EVENTS.SHOWDOWN_REVEALED }],
        },
        {
            id: 'showdown',
            content: 'game-the-gang:tutorial.steps.showdown',
            highlightTarget: 'the-gang-showdown-result',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'showdown-reading',
            content: 'game-the-gang:tutorial.steps.showdownReading',
            highlightTarget: 'the-gang-showdown-hole-cards',
            position: 'left',
            infoStep: true,
            viewAs: '0',
        },
        {
            id: 'finish',
            content: 'game-the-gang:tutorial.steps.finish',
            highlightTarget: 'the-gang-title',
            position: 'bottom',
            infoStep: true,
            showMask: true,
            viewAs: '0',
        },
    ],
};

export default TheGangTutorial;
