"""Export the installed TTS Die_12 mesh/UVs and number atlas used by Mage Wars.

Requires UnityPy, numpy and Pillow. Run from the repository root:
python scripts/assets/export-mage-wars-effect-die.py <Tabletop Simulator_Data> <Workshop JSON>
Then: npm run compress:images -- public/assets/i18n/zh-CN/mage-wars/dice
No screenshots, invented glyphs or per-result relabelling enter the runtime assets.
"""
import argparse
import json
import math
from pathlib import Path

import numpy as np
import UnityPy
from UnityPy.helpers.MeshHelper import MeshHandler


def find_die(value):
    if isinstance(value, dict):
        if value.get('GUID') == 'f9cb19':
            return value
        children = value.values()
    elif isinstance(value, list):
        children = value
    else:
        return None
    for child in children:
        found = find_die(child)
        if found:
            return found
    return None


def rounded(value):
    if isinstance(value, float):
        return round(value, 7)
    if isinstance(value, list):
        return [rounded(item) for item in value]
    if isinstance(value, dict):
        return {key: rounded(item) for key, item in value.items()}
    return value


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('data_dir', type=Path)
    parser.add_argument('workshop_json', type=Path)
    args = parser.parse_args()
    env = UnityPy.load(str(args.data_dir / 'resources.assets'))
    objects = {obj.path_id: obj for obj in env.objects if obj.assets_file.name == 'resources.assets'}
    die = find_die(json.loads(args.workshop_json.read_text(encoding='utf8')))
    assert die and die['Name'] == 'Die_12'
    prefab = objects[4352].read_typetree()
    assert prefab['m_Name'] == 'Die_12'
    components = {entry['component']['m_PathID'] for entry in prefab['m_Component']}
    assert {14037, 13467} <= components
    renderer = objects[13467].read_typetree()
    assert [mat['m_PathID'] for mat in renderer['m_Materials']] == [58, 54]
    mesh_filter = objects[14037].parse_as_object()
    mesh = mesh_filter.m_Mesh.read()
    assert mesh.m_Name == 'Dodecahedron' and mesh_filter.m_Mesh.path_id == 1971
    handler = MeshHandler(mesh)
    handler.process()
    vertices = np.array(handler.m_Vertices) * [1, -1, -1]
    uv = np.array(handler.m_UV0)[:, :2] * [1, -1] + [0, 1]
    assert len(vertices) == 60
    diameter = 2 * max(np.linalg.norm(point) for point in vertices)
    rotations = {}
    for entry in die['RotationValues']:
        x = math.radians(entry['Rotation']['x'])
        z = math.radians(entry['Rotation']['z'])
        rotations[int(entry['Value'])] = [math.sin(z) * math.cos(x), -math.cos(z) * math.cos(x), math.sin(x)]
    faces = []
    for index in range(12):
        vs, us = vertices[index * 5:index * 5 + 5], uv[index * 5:index * 5 + 5]
        a, b, offset = np.linalg.lstsq(np.column_stack([us, np.ones(5)]), vs, rcond=None)[0]
        u, v = a / np.linalg.norm(a), b / np.linalg.norm(b)
        normal = np.cross(u, v)
        value = max(rotations, key=lambda key: np.dot(normal, rotations[key]))
        assert np.dot(normal, rotations[value]) > 0.9999
        assert np.max(np.abs(us[:, 0, None] * a + us[:, 1, None] * b + offset - vs)) < 0.00001
        lo, hi = us.min(axis=0), us.max(axis=0)
        size = hi - lo
        corners = sorted(us.tolist(), key=lambda point: math.atan2(point[1] - us[:, 1].mean(), point[0] - us[:, 0].mean()))
        faces.append(dict(value=value, u=u.tolist(), v=v.tolist(), normal=normal.tolist(),
                          center=((a * (lo[0] + hi[0]) / 2 + b * (lo[1] + hi[1]) / 2 + offset) / diameter).tolist(),
                          width=float(np.linalg.norm(a) * size[0] / diameter),
                          height=float(np.linalg.norm(b) * size[1] / diameter),
                          uvMin=lo.tolist(), uvSize=size.tolist(),
                          clip=[((np.array(corner) - lo) / size).tolist() for corner in corners]))
    assert sorted(face['value'] for face in faces) == list(range(1, 13))
    header = ('// Generated by scripts/assets/export-mage-wars-effect-die.py.\n'
              '// TTS resources.assets: Die_12 (4352) -> MeshFilter (14037) -> Dodecahedron (1971).\n'
              '// Source vertices and UV0; Unity axes map to CSS as (x, -y, -z).\n'
              '// Face values derive from Workshop 2607721556 / f9cb19 RotationValues.\n')
    Path('src/games/mage-wars/ui/effectDieGeometry.ts').write_text(
        header + 'export const EFFECT_DIE_FACES = [\n' + ''.join(
            '    ' + json.dumps(rounded(face), separators=(', ', ': ')) + ',\n' for face in faces
        ) + '] as const;\n', encoding='utf8')
    material = objects[54].read_typetree()
    assert material['m_Name'] == 'Dice_NumbersWhite'
    texture_id = dict(material['m_SavedProperties']['m_TexEnvs'])['_MainTex']['m_Texture']['m_PathID']
    assert texture_id == 479
    cutoff = dict(material['m_SavedProperties']['m_Floats'])['_Cutoff']
    image = objects[texture_id].parse_as_object().image.convert('RGBA')
    image.putalpha(image.getchannel('A').point(lambda alpha: 255 if alpha / 255 >= cutoff else 0))
    image.save('public/assets/i18n/zh-CN/mage-wars/dice/effect-die-numbers.png')
    print('Exported 12 native mesh faces and 2048x2048 number atlas; alpha cutoff:', cutoff)


if __name__ == '__main__':
    main()
