import type { TokenDef } from '../../domain/tokenTypes';
import type { PassiveAbilityDef } from '../../domain/passiveAbility';
import { DICETHRONE_STATUS_ATLAS_IDS, STATUS_IDS, TOKEN_IDS } from '../../domain/ids';
import { ARTIFICER_SFX_ELECTRIC, ARTIFICER_SFX_METAL } from './abilities';

const tokenText = (id: string, field: 'name' | 'description') => `tokens.${id}.${field}`;
const statusText = (id: string, field: 'name' | 'description') => `statusEffects.${id}.${field}`;

export const ARTIFICER_TOKENS: TokenDef[] = [
    {
        id: TOKEN_IDS.SYNTH,
        name: tokenText(TOKEN_IDS.SYNTH, 'name'),
        colorTheme: 'from-cyan-300 to-slate-700',
        description: tokenText(TOKEN_IDS.SYNTH, 'description') as unknown as string[],
        iconPath: 'dicethrone/images/artificial/status/合成器',
        stackLimit: 7,
        category: 'consumable',
        sfxKey: ARTIFICER_SFX_METAL,
        frameId: 'synth',
        atlasId: DICETHRONE_STATUS_ATLAS_IDS.ARTIFICER,
    },
    {
        id: STATUS_IDS.NANOBOMB,
        name: statusText(STATUS_IDS.NANOBOMB, 'name'),
        colorTheme: 'from-rose-500 to-slate-950',
        description: statusText(STATUS_IDS.NANOBOMB, 'description') as unknown as string[],
        iconPath: 'dicethrone/images/artificial/status/纳米爆蛋',
        stackLimit: 3,
        category: 'debuff',
        sfxKey: ARTIFICER_SFX_ELECTRIC,
        passiveTrigger: {
            timing: 'onPhaseEnter',
            removable: true,
            actions: [],
        },
        frameId: 'nanobomb',
        atlasId: DICETHRONE_STATUS_ATLAS_IDS.ARTIFICER,
    },
    {
        id: TOKEN_IDS.NANOBOT,
        name: tokenText(TOKEN_IDS.NANOBOT, 'name'),
        colorTheme: 'from-emerald-300 to-teal-800',
        description: tokenText(TOKEN_IDS.NANOBOT, 'description') as unknown as string[],
        iconPath: 'dicethrone/images/artificial/status/纳米机器人1次使用机会',
        stackLimit: 1,
        category: 'consumable',
        sfxKey: ARTIFICER_SFX_METAL,
        passiveTrigger: {
            timing: 'onPhaseEnter',
            removable: false,
            actions: [],
        },
        frameId: 'nanobot',
        atlasId: DICETHRONE_STATUS_ATLAS_IDS.ARTIFICER,
    },
    {
        id: TOKEN_IDS.SHOCK_BOT,
        name: tokenText(TOKEN_IDS.SHOCK_BOT, 'name'),
        colorTheme: 'from-sky-300 to-indigo-800',
        description: tokenText(TOKEN_IDS.SHOCK_BOT, 'description') as unknown as string[],
        iconPath: 'dicethrone/images/artificial/status/电能机器人1次使用机会',
        stackLimit: 1,
        category: 'consumable',
        sfxKey: ARTIFICER_SFX_ELECTRIC,
        passiveTrigger: {
            timing: 'onPhaseEnter',
            removable: false,
            actions: [],
        },
        activeUse: {
            timing: ['beforeDamageDealt'],
            consumeAmount: 1,
            additionalTokenCosts: [{
                tokenId: TOKEN_IDS.SYNTH,
                amount: 2,
                overrideWhenOwnerTokenLimitAtLeast: {
                    limit: 2,
                    amount: 1,
                },
            }],
            requiresAttackDamage: true,
            effect: { type: 'modifyDamageDealt', value: 3 },
        },
        frameId: 'shock_bot',
        atlasId: DICETHRONE_STATUS_ATLAS_IDS.ARTIFICER,
    },
    {
        id: TOKEN_IDS.HEAL_BOT,
        name: tokenText(TOKEN_IDS.HEAL_BOT, 'name'),
        colorTheme: 'from-lime-300 to-green-800',
        description: tokenText(TOKEN_IDS.HEAL_BOT, 'description') as unknown as string[],
        iconPath: 'dicethrone/images/artificial/status/治疗机器人1次使用机会',
        stackLimit: 1,
        category: 'consumable',
        sfxKey: ARTIFICER_SFX_METAL,
        passiveTrigger: {
            timing: 'onPhaseEnter',
            removable: false,
            actions: [],
        },
        activeUse: {
            timing: ['beforeDamageReceived'],
            consumeAmount: 1,
            additionalTokenCosts: [{
                tokenId: TOKEN_IDS.SYNTH,
                amount: 2,
                overrideWhenOwnerTokenLimitAtLeast: {
                    limit: 2,
                    amount: 1,
                },
            }],
            requiresAttackDamage: true,
            minimumAttackDamage: 6,
            customActionId: 'artificer-heal-bot-use',
            effect: { type: 'modifyDamageReceived', value: 0 },
        },
        frameId: 'heal_bot',
        atlasId: DICETHRONE_STATUS_ATLAS_IDS.ARTIFICER,
    },
];

export const ARTIFICER_PASSIVE_ABILITIES: PassiveAbilityDef[] = [
    {
        id: 'artificer-workshop',
        nameKey: 'abilities.collect-parts.name',
        actions: [
            {
                type: 'custom',
                labelKey: 'tokens.nanobot.name',
                cpCost: 0,
                tokenCosts: [
                    { tokenId: TOKEN_IDS.NANOBOT, amount: 1 },
                    { tokenId: TOKEN_IDS.SYNTH, amount: 2 },
                ],
                requiresTokenLimitBelow: { tokenId: TOKEN_IDS.NANOBOT, limit: 2 },
                timing: 'ownUpkeepPhase',
                descriptionKey: 'tokens.nanobot.description',
                customActionId: 'artificer-nanobot-detonate',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.activateNanobotAdvancedShort',
                cpCost: 0,
                tokenCosts: [
                    { tokenId: TOKEN_IDS.NANOBOT, amount: 1 },
                    { tokenId: TOKEN_IDS.SYNTH, amount: 1 },
                ],
                requiresTokens: [{ tokenId: TOKEN_IDS.NANOBOT, amount: 1 }],
                requiresTokenLimitAtLeast: { tokenId: TOKEN_IDS.NANOBOT, limit: 2 },
                timing: 'ownUpkeepPhase',
                descriptionKey: 'passive.artificerWorkshop.activateNanobotAdvanced',
                customActionId: 'artificer-nanobot-detonate',
            },
            {
                type: 'custom',
                labelKey: 'statusEffects.nanobomb.name',
                cpCost: 0,
                tokenCost: { tokenId: TOKEN_IDS.SYNTH, amount: 4 },
                timing: 'anytime',
                descriptionKey: 'abilities.collect-parts.effects.spendSynthForNanobomb',
                customActionId: 'artificer-synth-inflict-nanobomb',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.buildNanobotShort',
                cpCost: 0,
                tokenCosts: [{ tokenId: TOKEN_IDS.SYNTH, amount: 2 }],
                requiresTokenBelowLimit: { tokenId: TOKEN_IDS.NANOBOT },
                timing: 'ownMainPhase',
                descriptionKey: 'passive.artificerWorkshop.buildNanobot',
                customActionId: 'artificer-build-nanobot',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.buildShockBotShort',
                cpCost: 0,
                tokenCosts: [{ tokenId: TOKEN_IDS.SYNTH, amount: 2 }],
                requiresTokenBelowLimit: { tokenId: TOKEN_IDS.SHOCK_BOT },
                timing: 'ownMainPhase',
                descriptionKey: 'passive.artificerWorkshop.buildShockBot',
                customActionId: 'artificer-build-shock-bot',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.buildHealBotShort',
                cpCost: 0,
                tokenCosts: [{ tokenId: TOKEN_IDS.SYNTH, amount: 2 }],
                requiresTokenBelowLimit: { tokenId: TOKEN_IDS.HEAL_BOT },
                timing: 'ownMainPhase',
                descriptionKey: 'passive.artificerWorkshop.buildHealBot',
                customActionId: 'artificer-build-heal-bot',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.upgradeNanobotShort',
                cpCost: 0,
                tokenCosts: [{ tokenId: TOKEN_IDS.SYNTH, amount: 3 }],
                requiresTokens: [{ tokenId: TOKEN_IDS.NANOBOT, amount: 1 }],
                requiresTokenLimitBelow: { tokenId: TOKEN_IDS.NANOBOT, limit: 2 },
                timing: 'ownMainPhase',
                descriptionKey: 'passive.artificerWorkshop.upgradeNanobot',
                customActionId: 'artificer-upgrade-nanobot',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.upgradeShockBotShort',
                cpCost: 0,
                tokenCosts: [{ tokenId: TOKEN_IDS.SYNTH, amount: 3 }],
                requiresTokens: [{ tokenId: TOKEN_IDS.SHOCK_BOT, amount: 1 }],
                requiresTokenLimitBelow: { tokenId: TOKEN_IDS.SHOCK_BOT, limit: 2 },
                timing: 'ownMainPhase',
                descriptionKey: 'passive.artificerWorkshop.upgradeShockBot',
                customActionId: 'artificer-upgrade-shock-bot',
            },
            {
                type: 'custom',
                labelKey: 'passive.artificerWorkshop.upgradeHealBotShort',
                cpCost: 0,
                tokenCosts: [{ tokenId: TOKEN_IDS.SYNTH, amount: 3 }],
                requiresTokens: [{ tokenId: TOKEN_IDS.HEAL_BOT, amount: 1 }],
                requiresTokenLimitBelow: { tokenId: TOKEN_IDS.HEAL_BOT, limit: 2 },
                timing: 'ownMainPhase',
                descriptionKey: 'passive.artificerWorkshop.upgradeHealBot',
                customActionId: 'artificer-upgrade-heal-bot',
            },
        ],
    },
];

export const ARTIFICER_INITIAL_TOKENS: Record<string, number> = {
    [TOKEN_IDS.SYNTH]: 3,
    [STATUS_IDS.NANOBOMB]: 0,
    [TOKEN_IDS.NANOBOT]: 0,
    [TOKEN_IDS.SHOCK_BOT]: 0,
    [TOKEN_IDS.HEAL_BOT]: 0,
};
